---
name: protetiko.com
title: protetiko.com
description: Protetiko is the new standard in dental order management.
keywords: dental order management prosthetics
url: protetiko.com
baseurl: /test.protetiko.com
theme:
exclude:
- Gemfile
- Gemfile.lock
- README.md
- Rakefile
- vendor/bundle
- .gitignore
google_analytics:
defaults:
- scope:
    path: "assets/images"
  values:
    image: true
